# docker build -f docker/Dockerfile-local -t l3-app .
# docker run -d -p 8080:8080 --name l3-app l3-app

# Use OpenJDK as the base image
FROM eclipse-temurin:21-jdk

#  Copy the SSL certificate into the container
# COPY ./cert-file/cert.cer /usr/local/share/ca-certificates/cert.crt

# Install Maven for the build environment
# RUN update-ca-certificates
# RUN keytool -importcert \
#     -trustcacerts \
#     -alias company-root-ca \
#     -file /usr/local/share/ca-certificates/cert.crt \
#     -keystore "${JAVA_HOME}/lib/security/cacerts" \
#     -storepass changeit -noprompt

# Install Maven for the build environment
RUN apt-get update && apt-get install -y maven

# Set working directory
WORKDIR /app

# Expose application port
EXPOSE 8080

# Copy the application JAR file
COPY ./open-data-spaces-l3-public/ouranos-data-spaces-l3-authenticator-backend-cmp/ /app
RUN mvn clean install -DskipTests=true

# Build the environment for the ODS platform
RUN cp core/target/core-0.0.1-SNAPSHOT.jar app.jar

# Run the application
CMD ["java", "-jar", "app.jar"]
