# =========================
# SOURCE: Forwarded from Docker/Compose
# =========================
<source>
  @type forward
  @id forward_input
  port 24224
  bind 0.0.0.0
</source>

# =========================
# FILTER: Drop empty message/log entries; extract "log"
# =========================
<filter **>
  @type grep
  <regexp>
    key log
    pattern .+
  </regexp>
</filter>

# Trailing newline
# <filter **>
#   @type record_transformer
#   enable_ruby true
#   <record>
#     log ${record["log"].to_s.chomp}
#   </record>
# </filter>

# =========================
# MATCH: Route logs to MinIO (S3-compatible backend)
# =========================
<match **>
  @type s3

  aws_key_id     minio-sample #minio-pj-a-sbx
  aws_sec_key    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # SN7mbLGN7snFcAqH69egDnCa

  s3_bucket      pj-a-sbx
  s3_endpoint    http://minio:9000
  force_path_style true

  path           applogs/
  time_slice_format %Y%m%d-%H

  store_as gzip
  s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}

  <format>
    @type json
  </format>

  <buffer time>
    @type file
    path /tmp/fluentd-buf/minio

    timekey 3600
    timekey_use_utc false
    timekey_wait 300s

    flush_interval 10s
    flush_at_shutdown true
  </buffer>
</match>
