#!/bin/bash
set -eu

API_ENDPOINT="${API_ENDPOINT:-http://localhost:8083}"

apk add --no-cache curl jq >/dev/null 2>&1 || true


# Create a new store

echo "Creating User Store..."

USER_STORE_ID="$(curl -sS -X POST \
  "$API_ENDPOINT/stores" \
  -H "Content-Type: application/json" \
  -d @openfga/5-create-user-store.json \
  | jq -r '.id'
)"

echo "Create Store completed."
echo "USER_STORE_ID=$USER_STORE_ID"

# Create Model
MODEL_RESPONSE=$(curl -i -X POST \
  $API_ENDPOINT/stores/$USER_STORE_ID/authorization-models \
  -H "Content-Type: application/json" \
  -d @openfga/6-create-user-store-model.json
)

# Extract model_id
MODEL_ID=$(echo "$MODEL_RESPONSE" | grep -o '"authorization_model_id":"[^"]*"' | cut -d'"' -f4)

## L2 gateway openfga Configuration
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCKER_COMPOSE_FILE="$PROJECT_ROOT/l2/docker-compose.yml"

echo ""
echo "updating l2 docker-compose.yml"
if [ -f "$DOCKER_COMPOSE_FILE" ]; then
    # Update SYSTEM_CLIENT_SECRET
    store_id=$(printf '%s' "$USER_STORE_ID" | sed 's/[\/&]/\\&/g')
    sed -i "s|^\([[:space:]]*-[[:space:]]*FGA_STORE_ID=\).*|\1$store_id|" "$DOCKER_COMPOSE_FILE"
    
    model_id=$(printf '%s' "$MODEL_ID" | sed 's/[\/&]/\\&/g')
    sed -i "s|^\([[:space:]]*-[[:space:]]*FGA_MODEL_ID=\).*|\1$model_id|" "$DOCKER_COMPOSE_FILE"
    
    echo "l2 docker-compose.yml updated"
else
    echo "Warning: docker-compose.yml not found at $DOCKER_COMPOSE_FILE"
fi
echo ""

# Export user_store to the .env file
ENV_FILE="$SCRIPT_DIR/.env.userstore"
cat > "$ENV_FILE" << EOF
# OpenFGA Settings (generated by setup_openfga.sh)
USER_STORE_ID=$USER_STORE_ID
USER_MODEL_ID=$MODEL_ID
EOF


echo "User Store ID:  $USER_STORE_ID"
echo "User Model ID:  $MODEL_ID"
