#!/bin/bash

# ============================================
# OpenFGA セットアップスクリプト
# ============================================
# 機能:
#   1. OpenFGA Store/Model 作成
#   2. docker-compose.yml の環境変数を更新
#
# 使用方法:
#   ./setup_openfga.sh
#
# 権限付与は grant_permission.sh を使用してください
# ============================================

set -e  # エラー時に停止

# --------------------------------------------
# 設定
# --------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCKER_COMPOSE_FILE="$PROJECT_ROOT/payment/docker-compose.yml"

FGA_API_URL="${FGA_API_URL:-http://localhost:8083}"
STORE_NAME="${STORE_NAME:-api-authorization-store}"

echo "============================================"
echo "OpenFGA Setup Script"
echo "============================================"
echo "API URL: $FGA_API_URL"
echo "Project Root: $PROJECT_ROOT"
echo ""

# --------------------------------------------
# 1. 接続確認（リトライ付き）
# --------------------------------------------
echo "[1/4] Checking OpenFGA connection..."

MAX_RETRIES=30
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -s "$FGA_API_URL/healthz" > /dev/null 2>&1; then
        echo "✅ OpenFGA is running"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "  Waiting for OpenFGA... ($RETRY_COUNT/$MAX_RETRIES)"
    sleep 2
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo "❌ Error: Cannot connect to OpenFGA at $FGA_API_URL"
    exit 1
fi
echo ""

# --------------------------------------------
# 2. Store の作成
# --------------------------------------------
echo "[2/4] Creating store: $STORE_NAME"

STORE_RESPONSE=$(curl -s -X POST "$FGA_API_URL/stores" \
  -H "Content-Type: application/json" \
  -d "{\"name\": \"$STORE_NAME\"}")

# store_id を抽出
STORE_ID=$(echo "$STORE_RESPONSE" | grep -o '"id":"[^"]*"' | cut -d'"' -f4)

if [ -z "$STORE_ID" ]; then
    echo "❌ Error: Failed to create store"
    echo "Response: $STORE_RESPONSE"
    exit 1
fi

echo "✅ Store created: $STORE_ID"
echo ""

# --------------------------------------------
# 3. 認可モデルの登録
# --------------------------------------------
echo "[3/4] Creating authorization model..."

MODEL_RESPONSE=$(curl -s -X POST "$FGA_API_URL/stores/$STORE_ID/authorization-models" \
  -H "Content-Type: application/json" \
  -d '{
    "schema_version": "1.1",
    "type_definitions": [
      {"type": "user"},
      {
        "type": "role",
        "relations": {"member": {"this": {}}},
        "metadata": {"relations": {"member": {"directly_related_user_types": [{"type": "user"}]}}}
      },
      {
        "type": "api_endpoint",
        "relations": {"can_access": {"this": {}}},
        "metadata": {"relations": {"can_access": {"directly_related_user_types": [{"type": "user"}, {"type": "role", "relation": "member"}]}}}
      }
    ]
  }')

# model_id を抽出
MODEL_ID=$(echo "$MODEL_RESPONSE" | grep -o '"authorization_model_id":"[^"]*"' | cut -d'"' -f4)

if [ -z "$MODEL_ID" ]; then
    echo "❌ Error: Failed to create authorization model"
    echo "Response: $MODEL_RESPONSE"
    exit 1
fi

echo "✅ Authorization model created: $MODEL_ID"
echo ""

# --------------------------------------------
# 4. docker-compose.yml の更新
# --------------------------------------------
echo "[4/4] Updating docker-compose.yml..."

if [ -f "$DOCKER_COMPOSE_FILE" ]; then
    # AUTHZ_ENABLED を true に設定
    sed -i "s/AUTHZ_ENABLED: \"false\"/AUTHZ_ENABLED: \"true\"/" "$DOCKER_COMPOSE_FILE"

    # STORE_ID を更新
    sed -i "s/AUTHZ_OPENFGA_STORE_ID: \${AUTHZ_OPENFGA_STORE_ID:-[^}]*}/AUTHZ_OPENFGA_STORE_ID: \${AUTHZ_OPENFGA_STORE_ID:-$STORE_ID}/" "$DOCKER_COMPOSE_FILE"

    # MODEL_ID を更新
    sed -i "s/AUTHZ_OPENFGA_MODEL_ID: \${AUTHZ_OPENFGA_MODEL_ID:-[^}]*}/AUTHZ_OPENFGA_MODEL_ID: \${AUTHZ_OPENFGA_MODEL_ID:-$MODEL_ID}/" "$DOCKER_COMPOSE_FILE"

    echo "✅ docker-compose.yml updated"
else
    echo "⚠️  Warning: docker-compose.yml not found at $DOCKER_COMPOSE_FILE"
fi
echo ""

# --------------------------------------------
# .env ファイルに出力
# --------------------------------------------
ENV_FILE="$SCRIPT_DIR/.env.openfga"

cat > "$ENV_FILE" << EOF
# OpenFGA Settings (generated by setup_openfga.sh)
FGA_API_URL=$FGA_API_URL
FGA_STORE_ID=$STORE_ID
FGA_MODEL_ID=$MODEL_ID
EOF

# --------------------------------------------
# 結果出力
# --------------------------------------------
echo "============================================"
echo "Setup Complete!"
echo "============================================"
echo ""
echo "Store ID:  $STORE_ID"
echo "Model ID:  $MODEL_ID"
echo ""
echo "設定ファイル: $ENV_FILE"
echo ""
echo "# 次のステップ:"
echo "# 1. ユーザーに権限を付与:"
echo "#    ./grant_permission.sh <operator_id> <api_permission>"
echo "#"
echo "# 2. アプリを再起動:"
echo "#    cd $PROJECT_ROOT/docker && docker compose up -d"
echo ""
echo "# 利用可能なAPI権限:"
echo "| eligibility-post | POST | /api/v1/data-exchange/transaction/eligibility | 取引可否確認API |"
echo "| eligibility-non-fee-model-post | POST | /api/v1/data-exchange/non-fee-model/transaction/eligibility | 取引可否確認API(利用料モデル無) |"
echo "| data-exchange-post | POST | /api/v1/data-exchange/status | データ交換状態登録API |"
echo "| data-exchange-put | PUT | /api/v1/data-exchange/status | データ交換状態更新API |"
echo "| data-exchange-non-fee-model-post | POST | /api/v1/data-exchange/non-fee-model/confirm | データ交換取引金額確定API(利用料モデル無) |"
echo "| fee-model-post | POST | /api/v1/fee-model | 利用料モデル登録API |"
echo "| fee-model-get | GET | /api/v1/fee-model | 利用料モデル取得API |"
echo "| fee-model-put | PUT | /api/v1/fee-model/{id} | 利用料モデル更新API |"
echo "| fee-model-delete | DELETE | /api/v1/fee-model/{id} | 利用料モデル削除API |"
echo "| payment-post | POST | /api/v1/payment | 支払予定額算出API |"
echo "| billing-post | POST | /api/v1/billing | 請求予定額算出API |"
echo ""
