on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: open-dataspaces/L2-dp-webapi
          path: L2-dp-webapi
          token: ${{ secrets.SDK_CI }}

      - uses: actions/checkout@v6
        with:
          repository: open-dataspaces/L3-identity-component
          path: L3-identity-component
          token: ${{ secrets.SDK_CI }}

      - uses: actions/checkout@v6
        with:
          repository: open-dataspaces/DCS-Payment
          path: DCS-Payment
          token: ${{ secrets.SDK_CI }}

      - run: docker network create shared-network-ods
      - run: docker compose up -d
